### ISSUE TITLE
Problem with first run

### ISSUE THREAD

**Issue by pedrosodre** [sebastienvercammen/ptc-acc-gen#106]
Hi,

I just configured config.js manually and bought 2captcha, and when I run the makeaccounts.sh, it returns:
Creating account 0 of 20
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open './accounts.csv'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.<anonymous> (/root/ptc-acc-gen/PogoPlayer/pogo.js:6:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
Find the generated accounts in PogoPlayer/accounts.csv

**Comment by JRCrawford** [comment]
Just create a file ./accounts.csv then

**Comment by ShadowSonic** [comment]
Fixed the Readme about this problem.
