### ISSUE TITLE
Problem during creation of accounts

### ISSUE THREAD

**Issue by leohrs** [sebastienvercammen/ptc-acc-gen#91]
Problem while creating accounts.

It only creates two or three accounts and then shows the following error, after which it goes to the validation of tutorial.

Any ideas of what I could do to solve it?

Creating account 16 of 19
Start recaptcha solving
C:\ptc-acc\ptc-acc-gen\ptc-acc-gen\index.js:259
                                                        if(body.substring(0, 2) == "OK")
                                                               ^

TypeError: Cannot read property 'substring' of undefined
    at Request._callback (C:\ptc-acc\ptc-acc-gen\ptc-acc-gen\index.js:259:15)
    at self.callback (C:\ptc-acc\ptc-acc-gen\ptc-acc-gen\node_modules\request\request.js:186:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (C:\ptc-acc\ptc-acc-gen\ptc-acc-gen\node_modules\request\request.js:845:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);

**Comment by sebastienvercammen** [comment]
This error (previously line `index.js:259`) was part of the request to 2captcha. The request failed, returning an undefined body.

I've added basic error handling for this particular issue so you can see what the real problem is when a request fails. Try again and let me know if the error persists.

I also want to add that this part of the code wasn't added by me. In truth, it's one big block of ugly code and it should be reworked entirely. If I find the time, I'll do it myself, otherwise any PRs are always welcome.

**Comment by pedrosodre** [comment]
Hi @sebastienvercammen, I already tried lot of times, when it does not show error, it shows "Find the generated accounts in PogoPlayer/accounts.csv", but PogoPlayer/accounts.csv is empty!
