### ISSUE TITLE
Fetching RPC endpoint failed, received status code 3

### ISSUE THREAD

**Issue by armarton** [sebastienvercammen/ptc-acc-gen#99]
Everything goes well till the following:

```
Auth service: ptc, Username: <username>, Password: <password>, Location: <long,latt>
```

After that the following exception thrown:

```bash
Failed to initialize client for <username>... ERROR: { Error: operation timed out after 4915 ms, 5 tries with error: Fetching RPC endpoint failed, received status code 3
    at <path>ptc-acc-gen/node_modules/bluebird-retry/lib/bluebird-retry.js:109:35
    at tryCatcher (<path>ptc-acc-gen/node_modules/bluebird/js/release/util.js:16:23)
    at <path>ptc-acc-gen/node_modules/bluebird/js/release/catch_filter.js:24:41
    at tryCatcher (<path>ptc-acc-gen/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (<path>ptc-acc-gen/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (<path>ptc-acc-gen/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (<path>ptc-acc-gen/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (<path>ptc-acc-gen/node_modules/bluebird/js/release/promise.js:687:18)
    at Async._drainQueue (<path>ptc-acc-gen/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (<path>ptc-acc-gen/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (<path>ptc-acc-gen/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
  failure: 
   Error: Fetching RPC endpoint failed, received status code 3
       at Request.self.request [as _callback] (<path>ptc-acc-gen/node_modules/pogobuf/pogobuf/pogobuf.client.js:1084:36)
       at Request.self.callback (<path>ptc-acc-gen/node_modules/request/request.js:186:22)
       at emitTwo (events.js:106:13)
       at Request.emit (events.js:191:7)
       at Request.<anonymous> (<path>ptc-acc-gen/node_modules/request/request.js:1081:10)
       at emitOne (events.js:96:13)
       at Request.emit (events.js:188:7)
       at IncomingMessage.<anonymous> (<path>ptc-acc-gen/node_modules/request/request.js:1001:12)
       at IncomingMessage.g (events.js:292:16)
       at emitNone (events.js:91:20)
       at IncomingMessage.emit (events.js:185:7)
       at endReadableNT (_stream_readable.js:974:12)
       at _combinedTickCallback (internal/process/next_tick.js:74:11)
       at process._tickCallback (internal/process/next_tick.js:98:9),
  code: 'ETIMEDOUT' }
```

Operating system: Ubuntu 16.04
Node.js: 7.2.0

I think that something wrong with the ingame ToS, but I don't know what that code 3 means.
Please check it.

**Comment by sebastienvercammen** [comment]
As with several of the other previously closed issues (please do a search next time before asking), problems with account validation, not creation, should be addressed by PogoPlayer: https://github.com/MRokas/PogoPlayer.

Although these account validation scripts will soon become obsolete as I merge my latest work with PokémonGo-Map.

**Comment by armarton** [comment]
Thank you
